x=int(input("Enter any values:"))
y=int(input("Enter any values:"))
power=pow(x,y)
add=(x+y)
sub=(x-y)
mul=(x*y)
div=(x/y)
print("sum of {x} an {y} is {add}".format(x=x , y=y, add=add))
print("sum of {x} an {y} is {power}".format(x=x , y=y, power=power))
print("sum of {x} an {y} is {sub}".format(x=x , y=y, sub=sub))
print("sum of {x} an {y} is {mul}".format(x=x , y=y, mul=mul))
print("sum of {x} an {y} is {div}".format(x=x , y=y, div=div))

